directories:
  output: release
  buildResources: build
appId: gw.barmanager.pro
productName: BarManager Pro
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - node_modules/**/*
      - '!node_modules/.cache'
      - '!node_modules/@types'
      - '!node_modules/**/test'
      - '!node_modules/**/tests'
      - '!node_modules/**/*.md'
      - '!node_modules/**/*.ts'
      - '!node_modules/**/*.map'
asar: true
asarUnpack:
  - node_modules/better-sqlite3/**/*
win:
  target:
    - nsis
  icon: build/icon.ico
linux:
  target:
    - AppImage
    - deb
  icon: build/icon.png
electronVersion: 28.3.3
